### PR TITLE
feat: charts-v2

### PR DESCRIPTION
**Pull request by Xilesun**
# Description (需求描述)
跟其他区块统一，图表区块也以Collection为基础进行配置，并优化配置项，提升体验。

# Motivation (需求背景)
旧图表插件实现比较简单，图表区块也没有以Collection作为源数据来创建，不方便后续进一步扩展和优化功能。

# Key changes (关键改动）
新增`charts-v2`插件

# Test plan (测试计划)
## Suggestions (测试建议)
根据使用文档测试每一项功能。

## Underlying risk (潜在风险)
Identify any potential risks or issues that may arise from the new feature or modification.

# Showcase (结果展示）
image
image

### CODE REVIEW

**Comment by Xilesun** [comment]
Link T-235

**Comment by mz0in** [comment]
hello @Xilesun  , 

I passed by and  tried  the chartv2  ,  the Dimensions and filter options doesn't show the  Association fields , for a example if I had tow collection one for customer information and the other for customer orders , and I need to filter the order data on all female customer or in a certain region I will not be able to do that in the current draft ,beside is there will be a sql option which will be very handy  , 

Regards

**Comment by Xilesun** [comment]
Hi, @mz0in . Thanks for your feedback!

We plan to support Association fields, but it may not be included in this version due to complications and compatibility issues.

We have developed a SQL mode but it's currently hidden. Since all data blocks are based on Collection in Nocobase now. We believe maintaining consistency will allow for easy integration of advanced features in the future, like data linkage with other data blocks. However, we still leave possibility to support SQL mode in chart blocks.

**Comment by mz0in** [comment]
> Hi, @mz0in . Thanks for your feedback!
> 
> We plan to support Association fields, but it may not be included in this version due to complications and compatibility issues.
> 
> We have developed a SQL mode but it's currently hidden. Since all data blocks are based on Collection in Nocobase now. We believe maintaining consistency will allow for easy integration of advanced features in the future, like data linkage with other data blocks. However, we still leave possibility to support SQL mode in chart blocks.
> 
> thank you very much  , if you may consider also a table option in the chart type would be nice since it would be handy , meanwhile I think there is a need for a  plugins that can make a data block out of sql query without the need to create a collection connected to view which will simplify  applications development and make it faster ,also  this can avoid some complications and compatibility issue that would arise when  developing a new  plugin  that handles Association fields.

**Comment by Xilesun** [comment]
> > Hi, @mz0in . Thanks for your feedback!
> 
> thank you very much , if you may consider also a table option in the chart type would be nice since it would be handy , meanwhile I think there is a need for a plugins that can make a data block out of sql query without the need to create a collection connected to view which will simplify applications development and make it faster ,also this can avoid some complications and compatibility issue that would arise when developing a new plugin that handles Association fields.

Thanks for you valuable suggestions. As we have already provided table blocks, we won't include a table option in the current stage. The chart block in Nocobase is different from other professional BI applications. It is part of Nocobase and designed to be used alongside other data blocks. We offer APIs for integrating custom chart components for those who prefer alternative options. This is an initial version and we will continue to improve it in the future. 

Regarding SQL, Collection, and Database View, we aim to strike a balance and provide user-friendly features.

Appreciate for your attention and welcome any additional ideas.

**Comment by mz0in** [comment]
Thank you , looking for the future enhancement

**Comment by mz0in** [comment]
hello @Xilesun 
chart 2 is affecting the chart v1 when I'm trying to configure the chart v1 , the configuration window is disapering right away even when adding a new chart v1 the window will disappear , would you check the issue .
Thanks

**Comment by Xilesun** [comment]
> hello @Xilesun chart 2 is affecting the chart v1 when I'm trying to configure the chart v1 , the configuration window is disapering right away even when adding a new chart v1 the window will disappear , would you check the issue . Thanks

I couldn't reproduce it. Could you provide detailed steps? It is better to include a screen record.

**Comment by mz0in** [comment]
> > hello @Xilesun chart 2 is affecting the chart v1 when I'm trying to configure the chart v1 , the configuration window is disapering right away even when adding a new chart v1 the window will disappear , would you check the issue . Thanks
> 
> I couldn't reproduce it. Could you provide detailed steps? It is better to include a screen record.

hi   @Xilesun, it was fixed with the recent code updae  : 
@Xilesun
[feat(charts-v2): init chart config from query](https://github.com/nocobase/nocobase/pull/1965/commits/9af0f73b5ec7b854b6d6fa8c71437eb844fd4fe2)
 
[9af0f73](https://github.com/nocobase/nocobase/pull/1965/commits/9af0f73b5ec7b854b6d6fa8c71437eb844fd4fe2)
@Xilesun
[feat: change layout](https://github.com/nocobase/nocobase/pull/1965/commits/0a4f82f135d78f427f9ffdc986da05316f773b7d)

**Comment by Xilesun** [comment]
> the problem is not constant ,I'm not sure after which commit it happened
> 
> I think it was fixed at the the commit [feat: change layout](https://github.com/nocobase/nocobase/pull/1965/commits/0a4f82f135d78f427f9ffdc986da05316f773b7d)
> 
> and it was returned by commit @Xilesun [test: fix frontend test](https://github.com/nocobase/nocobase/pull/1965/commits/593b3d0ee45dd5a180e8fdbc36f7ad26dc23091f)
> 
> you can find the screen record
> 
>  Screen.Recording.2023-06-16.at.11.23.23.mov

Got it and I couldn't reproduce the issue on my device. This branch is still in testing and unstable. I will try to locate and fix it one the other issues done. Thanks for your patience.

**Comment by mz0in** [comment]
> > Hi, @mz0in . Thanks for your feedback!
> 
> thank you very much , if you may consider also a table option in the chart type would be nice since it would be handy , meanwhile I think there is a need for a plugins that can make a data block out of sql query without the need to create a collection connected to view which will simplify applications development and make it faster ,also this can avoid some complications and compatibility issue that would arise when developing a new plugin that handles Association fields.

sorry to come pack again , but every time I look at chart2 , I see potential to such an option .. 

Screenshot 2023-06-17 at 09 47 53

**Comment by Xilesun** [comment]
> > > Hi, @mz0in . Thanks for your feedback!
> > 
> > 
> > thank you very much , if you may consider also a table option in the chart type would be nice since it would be handy , meanwhile I think there is a need for a plugins that can make a data block out of sql query without the need to create a collection connected to view which will simplify applications development and make it faster ,also this can avoid some complications and compatibility issue that would arise when developing a new plugin that handles Association fields.
> 
> sorry to come pack again , but every time I look at chart2 , I see potential to such an option ..
> 
> Screenshot 2023-06-17 at 09 47 53

Appreciate for your feedback. Just to clarify your requests, are you suggesting that you would like to write SQL directly and have the results showed in a table format?

PS: 

> the problem is not constant ,I'm not sure after which commit it happened
> 
> I think it was fixed at the the commit [feat: change layout](https://github.com/nocobase/nocobase/pull/1965/commits/0a4f82f135d78f427f9ffdc986da05316f773b7d)
> 
> and it was returned by commit @Xilesun [test: fix frontend test](https://github.com/nocobase/nocobase/pull/1965/commits/593b3d0ee45dd5a180e8fdbc36f7ad26dc23091f)
> 
> you can find the screen record
> 
>  Screen.Recording.2023-06-16.at.11.23.23.mov

The issue you mentioned was found that it is a bug on `main` branch and will be fixed later.

**Comment by mz0in** [comment]
How 

> > > > Hi, @mz0in . Thanks for your feedback!
> > > 
> > > 
> > > thank you very much , if you may consider also a table option in the chart type would be nice since it would be handy , meanwhile I think there is a need for a plugins that can make a data block out of sql query without the need to create a collection connected to view which will simplify applications development and make it faster ,also this can avoid some complications and compatibility issue that would arise when developing a new plugin that handles Association fields.
> > 
> > 
> > sorry to come pack again , but every time I look at chart2 , I see potential to such an option ..
> > Screenshot 2023-06-17 at 09 47 53
> 
> Appreciate for your feedback. Just to clarify your requests, are you suggesting that you would like to write SQL directly and have the results showed in a table format?
> 
> PS:
> 
> > the problem is not constant ,I'm not sure after which commit it happened
> > I think it was fixed at the the commit [feat: change layout](https://github.com/nocobase/nocobase/pull/1965/commits/0a4f82f135d78f427f9ffdc986da05316f773b7d)
> > and it was returned by commit @Xilesun [test: fix frontend test](https://github.com/nocobase/nocobase/pull/1965/commits/593b3d0ee45dd5a180e8fdbc36f7ad26dc23091f)
> > you can find the screen record
> > Screen.Recording.2023-06-16.at.11.23.23.mov
> 
> The issue you mentioned was found that it is a bug on `main` branch and will be fixed later.

glad you found the bug .. 
yes , that's right , writing a sql query and having the result in table format would make it so practical and fast to present needed data besides other charts ,  it will be more informative .. the use of table format in sql will allow the use of not only table but also a pivot table which is far more helpful in charts and summarizing data results . 
The below image is a dash I wrote in bower bi , which some how shows how tables are  important and  informatics with charts.
Screenshot 2023-06-17 at 20 30 30


many thank with regards

**Comment by Xilesun** [comment]
@mz0in 

Thanks for taking the time to provide the details.

1. Currently, the result is displayed in JSON format in Data tab now, we are considering changing it to table format. If you want the table displayed on a page besides other charts, how about creating a table block? 

2. Regarding the SQL feature, we need to have an evaluation after this version released. May I inquire why you are not inclined to use the query configure pane? We can work on improving the user experience of it. Additionally, if you need to configure multiple charts with similar query configuration, you can utilize the duplicate function.

**Comment by mz0in** [comment]
> @mz0in
> 
> Thanks for taking the time to provide the details.
> 
> 1. Currently, the result is displayed in JSON format in Data tab now, we are considering changing it to table format. If you want the table displayed on a page besides other charts, how about creating a table block?
> 2. Regarding the SQL feature, we need to have an evaluation after this version released. May I inquire why you are not inclined to use the query configure pane? We can work on improving the user experience of it. Additionally, if you need to configure multiple charts with similar query configuration, you can utilize the duplicate function.

Thanks for your kindness 
so creating a table block in the current flow , will need extra work steps and will make the designing time extremely long and more complicated  ,since currently there is no table block from query option, 

like  this  case example .. I have  a couple of main tables , customer , order , order details , shipment , if I need  to represent the data of monthly and weekly sales order by customer and by product , and I need to have another table for yearly sales in general , and another for quarterly , and another for  quarterly target against real sales ,also with  aggregation level , by city , area , each customer and country .. etc .. I could have 4 tables , but I may need 100 different query to use in my dashboard combined of  tables and charts ,for practicality I should not go and make a new collection that  Connect to database view which mean I need to create a collection view for each query I have which mean : 
step 1 make view on the database level out side nocobase 
step 2 create a new collection connected to that view in the collection manager . 
step 3 configure the Field interface in  collection manager fro that view . 
step 4 adding a table block from that view 
the other issue that I will reserver extra  space in collection manager for each view I need which will complicate the general look of collection manager, 
.. while  adding a table block  from query can solve the need in 1 step which will only need to write the sql command. 
adding that in chart block or in table block it will be very handy .. 



I think you

**Comment by Xilesun** [comment]
@mz0in We highly value your suggestions. We had a discussion and here are the updates:
1. Table option will be added later.
2. SQL mode is being considered and we are working on finding a better way to implement this feature.

**Comment by mz0in** [comment]
hello , glad the table option is here that fast , 
if you allow me .. Association fields is not shown in the dimensions or filter ,
 the query also have been fixed in the lates commits . 

Screenshot 2023-06-19 at 12 33 08

Screenshot 2023-06-19 at 13 20 15

many thanks

**Comment by Xilesun** [comment]
#2160

**Pull request closed without merging**
