### PR TITLE
feat(client): allow JSON5 value in Form Input of type JSONTextArea

### PR DESCRIPTION
**Pull request by leptoquark1**
# Description
Allow client values of JSON5 for FormInput JSONTextArea. Persisting is kept in valid JSON.

# Motivation
The old JSON Input Field did not allow JSON5 (Human friendly JSON) input. Advanced chart configuration for example was painfully when validated for raw JSON.

# Key changes
- Frontend
  - Component schema of JSONTextArea adjusted to validate by JSON 5 when input is changed. State value is parsed to JSON. 
  - Additional boolean prop `json5` introduced (default=true) to disable this behaviour

### CODE REVIEW

**Comment by mytharcher** [comment]
Thanks for your contribution!

It looks useful. We may need some test on this feature.

**Comment by Xilesun** [comment]
Thanks a lot, @leptoquark1 

Could you add or edit a test here 
https://github.com/nocobase/nocobase/blob/main/packages/core/client/src/schema-component/antd/input/__tests__/Input.test.tsx

And an additional demo is better, you can run `yarn doc` under the root directory of the code base to launch the client demo site
https://github.com/nocobase/nocobase/blob/main/packages/core/client/src/schema-component/antd/input/index.en-US.md

**Comment by leptoquark1** [comment]
> Thanks a lot, @leptoquark1
> 
> Could you add or edit a test here https://github.com/nocobase/nocobase/blob/main/packages/core/client/src/schema-component/antd/input/__tests__/Input.test.tsx
> 
> And an additional demo is better, you can run `yarn doc` under the root directory of the code base to launch the client demo site https://github.com/nocobase/nocobase/blob/main/packages/core/client/src/schema-component/antd/input/index.en-US.md

I've put JSON5 as an example in the docs. The the are a little pitty for, as I'm on a windows atm and vitest won't run properly. I hope they pass anyhow

**Comment by 2013xile** [comment]
> > Thanks a lot, @leptoquark1
> > Could you add or edit a test here https://github.com/nocobase/nocobase/blob/main/packages/core/client/src/schema-component/antd/input/__tests__/Input.test.tsx
> > And an additional demo is better, you can run `yarn doc` under the root directory of the code base to launch the client demo site https://github.com/nocobase/nocobase/blob/main/packages/core/client/src/schema-component/antd/input/index.en-US.md
> 
> I've put JSON5 as an example in the docs. The tests are a little stubborn for me, as I'm on a windows atm and vitest won't run properly. I hope they pass anyhow

Got it. No worries. I would like to help fix it later. Thanks for your great work.

**Comment by leptoquark1** [comment]
@chareice @2013xile Thanks for the merge, but your changes in [2b9ce7b](https://github.com/nocobase/nocobase/pull/4600/commits/2b9ce7b2376bb65736d11f42d2459455e3b3c635) discarded exactly what the [motivation](#issue-2341262027) of this PR was :(

**Comment by 2013xile** [comment]
> @chareice @2013xile Thanks for the merge, but your changes in [2b9ce7b](https://github.com/nocobase/nocobase/pull/4600/commits/2b9ce7b2376bb65736d11f42d2459455e3b3c635) discarded exactly what the [motivation](#issue-2341262027) of this PR was :(

Just for ensuring compatibility, I set the default value of `json5` to `false`. It allows for the use of JSON5 syntax in chart json configurations via another  PR #4668

**Pull request merged**
