### PR TITLE
fix: acl data scope

### PR DESCRIPTION
**Pull request by lainlee**
数据表操作权限配置扩展
- 增加用户关系变量
- 增加时间变量

### CODE REVIEW

**Comment by JoGosGitHub** [comment]
Is this fixing the current rendering issue with ACL data scopes?
Rendering failed when accessing custom data scopes (ACL -> Configure -> Action Permissions -> Configure -> Individual -> Data Scope -> Add new -> Add condition)
If not I will create a new issue for this.

**Comment by lainlee** [comment]
> Is this fixing the current rendering issue with ACL data scopes? Rendering failed when accessing custom data scopes (ACL -> Configure -> Action Permissions -> Configure -> Individual -> Data Scope -> Add new -> Add condition) If not I will create a new issue for this.

Hi. Could you please describe the rendering issue in more details?
This PR fixes the following two issues. Maybe not as same as yours

- Add user relations variables when add condition in data scopes
- Add Date variables when add condition in data scopes

**Comment by JoGosGitHub** [comment]
Sure, I created a new issue #1846

**Comment by rouhu** [comment]
Can this be merged. It a show stopper still in v0.11.0.

**Pull request closed without merging**
