### PR TITLE
feat(database): support ssl config of database

### PR DESCRIPTION
**Pull request by chareice**
support connect to database server using ssl configuration. through this new env config:

```
DB_DIALECT_OPTIONS_SSL_CA=
DB_DIALECT_OPTIONS_SSL_KEY=
DB_DIALECT_OPTIONS_SSL_CERT=
DB_DIALECT_OPTIONS_SSL_REJECT_UNAUTHORIZED=true
```

### CODE REVIEW

**Comment by MisterKCloud** [comment]
@chareice 
There seems to be a problem, added the CA via the environment variables, but got following error messages. Could it be that the CA file in PEM format is not supported?

`#== SSL CONFIG ==#
 DB_DIALECT_OPTIONS_SSL_CA=/home/ubuntu/mysql-01_ca.pem
# DB_DIALECT_OPTIONS_SSL_KEY=
# DB_DIALECT_OPTIONS_SSL_CERT=
 DB_DIALECT_OPTIONS_SSL_REJECT_UNAUTHORIZED=true`

`ubuntu@ia**********:~/my-nocobase-app$ yarn nocobase install --lang=en-US
yarn run v1.22.19
$ nocobase install --lang=en-US
WAIT: TypeScript compiling...
add app main into supervisor
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 1
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 2
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 3
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 4
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 5
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 6
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 7
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 8
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 9
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 10
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 11
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 12
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 13
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 14
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 15
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 16
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 17
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 18
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 19
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 20
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 21
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 22
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 23
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 24
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 25
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 26
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 27
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 28
Unable to connect to the database: self signed certificate in certificate chain
reconnecting... 29
Unable to connect to the database: self signed certificate in certificate chain
/home/ubuntu/my-nocobase-app/packages/core/database/src/database.ts:713
          throw new Error('Connection failed, please check your database connection credentials and try again.');
                ^

Error: Connection failed, please check your database connection credentials and try again.
    at authenticate (/home/ubuntu/my-nocobase-app/packages/core/database/src/database.ts:713:17)
    at authenticate (/home/ubuntu/my-nocobase-app/packages/core/database/src/database.ts:718:16)
    at authenticate (/home/ubuntu/my-nocobase-app/packages/core/database/src/database.ts:718:16)
    at authenticate (/home/ubuntu/my-nocobase-app/packages/core/database/src/database.ts:718:16)
    at authenticate (/home/ubuntu/my-nocobase-app/packages/core/database/src/database.ts:718:16)
    at authenticate (/home/ubuntu/my-nocobase-app/packages/core/database/src/database.ts:718:16)
    at authenticate (/home/ubuntu/my-nocobase-app/packages/core/database/src/database.ts:718:16)
    at authenticate (/home/ubuntu/my-nocobase-app/packages/core/database/src/database.ts:718:16)
    at authenticate (/home/ubuntu/my-nocobase-app/packages/core/database/src/database.ts:718:16)
    at authenticate (/home/ubuntu/my-nocobase-app/packages/core/database/src/database.ts:718:16)
Done in 19.50s`

**Comment by chareice** [comment]
@MisterKCloud Please try set `DB_DIALECT_OPTIONS_SSL_REJECT_UNAUTHORIZED=false`, and the value of `DB_DIALECT_OPTIONS_SSL_CA` to the full content of the SSL CA instead of the path.

**Comment by MisterKCloud** [comment]
@chareice Do set the flag `DB_DIALECT_OPTIONS_SSL_REJECT_UNAUTHORIZED=false` is not an option!!! As it would tell the client to ignore SSL validation errors. From security perspective this is an absolute NOGO.

I tested various scenarios for `DB_DIALECT_OPTIONS_SSL_CA`:
* Path PEM file
* Path to CRT file
* Content of PEM file
* Content of CRT file

All variants resulted in the same error. Is there any option to increase log/debug level to see if the used framework is also utilizing the value of `DB_DIALECT_OPTIONS_SSL_CA` ?

Or any other idea how to debug it?

PS: If I set `DB_DIALECT_OPTIONS_SSL_REJECT_UNAUTHORIZED=false` as you recommended the connection works of course.

**Comment by chareice** [comment]
> @chareice Do set the flag `DB_DIALECT_OPTIONS_SSL_REJECT_UNAUTHORIZED=false` is not an option!!! As it would tell the client to ignore SSL validation errors. From security perspective this is an absolute NOGO.
> 
> I tested various scenarios for `DB_DIALECT_OPTIONS_SSL_CA`:
> 
> * Path PEM file
> * Path to CRT file
> * Content of PEM file
> * Content of CRT file
> 
> All variants resulted in the same error. Is there any option to increase log/debug level to see if the used framework is also utilizing the value of `DB_DIALECT_OPTIONS_SSL_CA` ?
> 
> Or any other idea how to debug it?
> 
> PS: If I set `DB_DIALECT_OPTIONS_SSL_REJECT_UNAUTHORIZED=false` as you recommended the connection works of course.

Thank you for your feedback. I will conduct a thorough test to fully understand the issue.

**Comment by chareice** [comment]
@MisterKCloud A new PR has been merged https://github.com/nocobase/nocobase/pull/2689.  Please try configuring the following environment variables:
```
DB_DIALECT_OPTIONS_SSL_MODE=VERIFY_IDENTITY
DB_DIALECT_OPTIONS_SSL_CA=${replace with your CA file path}
```

**Comment by MisterKCloud** [comment]
Thank you @chareice it seems working. 🥇 

Following settings have been used for my test run:
#== SSL CONFIG ==#
DB_DIALECT_OPTIONS_SSL_CA=/path/to/my.pem
DB_DIALECT_OPTIONS_SSL_REJECT_UNAUTHORIZED=true
DB_DIALECT_OPTIONS_SSL_MODE=VERIFY_IDENTITY

**Pull request merged**
