### PR TITLE
feat(mysql): have CA.pem for mysql

### PR DESCRIPTION
**Pull request by tkamsker**
> **Note**
> This is a template for submitting a new feature. Use the bug fix template if you're submitting a bug fix pull request by adding `template=bug_fix.md` to your pull request URL.

# Description (需求描述)
We needed possibility to add an CA.PEM file for use mysql from our cloud provider 

# Motivation (需求背景)
Safe connection to mysql cloud database 
# Key changes (关键改动）
Provide a technically detailed description of the key changes made.
- Frontend (前端)none 
- Backend (后端)
we added an new value DB_CAPATh where you can set the path to the CA.PEM file 
for mysql. 
similar like DB_CAPATH=/Users/root/Downloads/ca.pem

# Test plan (测试计划)
Compile and access database 
we added an new table and checked if in the cloud the table shows 

## Suggestions (测试建议)
Provide any suggestions or recommendations for improvements in the testing plan.

## Underlying risk (潜在风险)
Identify any potential risks or issues that may arise from the new feature or modification.
we can not see any risk it was an necessarily 

# Showcase (结果展示）
Including any screenshots of the new feature or modification.
no screenshot avail

### CODE REVIEW

**Comment by tkamsker** [comment]
All this tests where in wrong before and are not touching our change so i cant fix sqlite and postgres errors so maybe the tests need rework ...

**Comment by chareice** [comment]
@tkamsker Please check for failed test cases
image

**Comment by MisterKCloud** [comment]
@chareice for your info, the tests have been passed now. @tkamsker fixed it.

**Comment by chareice** [comment]
@tkamsker @MisterKCloud  Given that this is a common requirement to connect to the database server using SSL, we will close this PR. Please try this new PR to see if it resolves your issue. Thank you.  https://github.com/nocobase/nocobase/pull/2620

**Pull request closed without merging**
